name: spendify
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.2
  firebase_storage: ^11.7.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.0
  fluttertoast: ^8.2.5
  image_picker: ^1.1.0
  intl: ^0.19.0
  math_expressions: ^2.5.0
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pie_chart: ^5.4.0
  progress_dialog_null_safe: ^3.0.0
  shared_preferences: ^2.2.3
  workmanager: ^0.5.2
  timezone: ^0.9.2
  firebase_core: ^2.30.0
  syncfusion_flutter_calendar: ^25.1.41
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
